<?php

namespace ContainerWBcagpb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllerproductsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IAVS8nf.App\Controller\ApiController::products()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IAVS8nf.App\\Controller\\ApiController::products()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ProductRepository',
        ]))->withContext('App\\Controller\\ApiController::products()', $container);
    }
}
