<?php

namespace ContainerKbGiPCv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7lckEhVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7lckEhV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AccountController::index' => ['privates', '.service_locator.iOBMqcQ.App\\Controller\\AccountController::index()', 'getAccountControllerindexService', true],
            'App\\Controller\\AccountController::toggleApi' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\AccountController::toggleApi()', 'getAccountControllertoggleApiService', true],
            'App\\Controller\\AccountController::deleteAccount' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\AccountController::deleteAccount()', 'getAccountControllerdeleteAccountService', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.t8QaZRa.App\\Controller\\CartController::index()', 'getCartControllerindexService', true],
            'App\\Controller\\CartController::add' => ['privates', '.service_locator.uqMdrhc.App\\Controller\\CartController::add()', 'getCartControlleraddService', true],
            'App\\Controller\\CartController::clear' => ['privates', '.service_locator.rzdOKy_.App\\Controller\\CartController::clear()', 'getCartControllerclearService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.qHOVbN9.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AccountController:index' => ['privates', '.service_locator.iOBMqcQ.App\\Controller\\AccountController::index()', 'getAccountControllerindexService', true],
            'App\\Controller\\AccountController:toggleApi' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\AccountController::toggleApi()', 'getAccountControllertoggleApiService', true],
            'App\\Controller\\AccountController:deleteAccount' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\AccountController::deleteAccount()', 'getAccountControllerdeleteAccountService', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.t8QaZRa.App\\Controller\\CartController::index()', 'getCartControllerindexService', true],
            'App\\Controller\\CartController:add' => ['privates', '.service_locator.uqMdrhc.App\\Controller\\CartController::add()', 'getCartControlleraddService', true],
            'App\\Controller\\CartController:clear' => ['privates', '.service_locator.rzdOKy_.App\\Controller\\CartController::clear()', 'getCartControllerclearService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.qHOVbN9.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AccountController::index' => '?',
            'App\\Controller\\AccountController::toggleApi' => '?',
            'App\\Controller\\AccountController::deleteAccount' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\CartController::add' => '?',
            'App\\Controller\\CartController::clear' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AccountController:index' => '?',
            'App\\Controller\\AccountController:toggleApi' => '?',
            'App\\Controller\\AccountController:deleteAccount' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\CartController:add' => '?',
            'App\\Controller\\CartController:clear' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);

        if (isset($container->privates['.service_locator.7lckEhV'])) {
            return $container->privates['.service_locator.7lckEhV'];
        }

        return $container->privates['.service_locator.7lckEhV'] = $instance;
    }
}
