<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWBcagpb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWBcagpb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWBcagpb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWBcagpb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWBcagpb\App_KernelDevDebugContainer([
    'container.build_hash' => 'WBcagpb',
    'container.build_id' => 'fc57c2b3',
    'container.build_time' => 1775495237,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWBcagpb');
