<?php

namespace ContainerIYvDM4b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllerclearService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rzdOKy_.App\Controller\CartController::clear()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartRepository' => ['privates', 'App\\Repository\\CartRepository', 'getCartRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'cartRepository' => 'App\\Repository\\CartRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\CartController::clear()', $container);

        if (isset($container->privates['.service_locator.rzdOKy_.App\\Controller\\CartController::clear()'])) {
            return $container->privates['.service_locator.rzdOKy_.App\\Controller\\CartController::clear()'];
        }

        return $container->privates['.service_locator.rzdOKy_.App\\Controller\\CartController::clear()'] = $instance;
    }
}
