<?php

namespace ContainerWBcagpb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t8QaZRa.App\Controller\CartController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t8QaZRa.App\\Controller\\CartController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartRepository' => ['privates', 'App\\Repository\\CartRepository', 'getCartRepositoryService', true],
        ], [
            'cartRepository' => 'App\\Repository\\CartRepository',
        ]))->withContext('App\\Controller\\CartController::index()', $container);
    }
}
