# config/services.yaml

parameters: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"
        exclude:
            - "../src/Kernel.php"
            - "../src/Entity/"

    App\Service\CartService:
        arguments:
            $sessionFactory: "@session.factory"
