<?php

namespace ContainerK7Jz09T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControlleraddService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uqMdrhc.App\Controller\CartController::add()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'product' => ['privates', '.errored..service_locator.uqMdrhc.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.uqMdrhc": it needs an instance of "App\\Entity\\Product" but this type has been excluded because it\'s a Doctrine entity.'],
            'cartRepository' => ['privates', 'App\\Repository\\CartRepository', 'getCartRepositoryService', true],
            'cartItemRepository' => ['privates', 'App\\Repository\\CartItemRepository', 'getCartItemRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'product' => 'App\\Entity\\Product',
            'cartRepository' => 'App\\Repository\\CartRepository',
            'cartItemRepository' => 'App\\Repository\\CartItemRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\CartController::add()', $container);

        if (isset($container->privates['.service_locator.uqMdrhc.App\\Controller\\CartController::add()'])) {
            return $container->privates['.service_locator.uqMdrhc.App\\Controller\\CartController::add()'];
        }

        return $container->privates['.service_locator.uqMdrhc.App\\Controller\\CartController::add()'] = $instance;
    }
}
