<?php

namespace ContainerG8w4jZf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UKVjWMsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UKVjWMs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.t8QaZRa.App\\Controller\\CartController::index()', 'getCartControllerindexService', true],
            'App\\Controller\\CartController::add' => ['privates', '.service_locator.uqMdrhc.App\\Controller\\CartController::add()', 'getCartControlleraddService', true],
            'App\\Controller\\CartController::clear' => ['privates', '.service_locator.rzdOKy_.App\\Controller\\CartController::clear()', 'getCartControllerclearService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.qHOVbN9.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.t8QaZRa.App\\Controller\\CartController::index()', 'getCartControllerindexService', true],
            'App\\Controller\\CartController:add' => ['privates', '.service_locator.uqMdrhc.App\\Controller\\CartController::add()', 'getCartControlleraddService', true],
            'App\\Controller\\CartController:clear' => ['privates', '.service_locator.rzdOKy_.App\\Controller\\CartController::clear()', 'getCartControllerclearService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.qHOVbN9.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\CartController::add' => '?',
            'App\\Controller\\CartController::clear' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\CartController:add' => '?',
            'App\\Controller\\CartController:clear' => '?',
            'App\\Controller\\ProductController:show' => '?',
        ]);

        if (isset($container->privates['.service_locator.UKVjWMs'])) {
            return $container->privates['.service_locator.UKVjWMs'];
        }

        return $container->privates['.service_locator.UKVjWMs'] = $instance;
    }
}
