<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUhf66pT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUhf66pT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUhf66pT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUhf66pT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUhf66pT\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uhf66pT',
    'container.build_id' => '3adeff73',
    'container.build_time' => 1776535255,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUhf66pT');
