<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_account' => [[], ['_controller' => 'App\\Controller\\AccountController::index'], [], [['text', '/mon-compte']], [], [], []],
    'app_account_toggle_api' => [[], ['_controller' => 'App\\Controller\\AccountController::toggleApi'], [], [['text', '/mon-compte/api/toggle']], [], [], []],
    'app_account_delete' => [[], ['_controller' => 'App\\Controller\\AccountController::deleteAccount'], [], [['text', '/mon-compte/supprimer']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegisterController::index'], [], [['text', '/register']], [], [], []],
    'app_security' => [[], ['_controller' => 'App\\Controller\\SecurityController::index'], [], [['text', '/security']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\AccountController::index' => [[], ['_controller' => 'App\\Controller\\AccountController::index'], [], [['text', '/mon-compte']], [], [], []],
    'App\Controller\AccountController::toggleApi' => [[], ['_controller' => 'App\\Controller\\AccountController::toggleApi'], [], [['text', '/mon-compte/api/toggle']], [], [], []],
    'App\Controller\AccountController::deleteAccount' => [[], ['_controller' => 'App\\Controller\\AccountController::deleteAccount'], [], [['text', '/mon-compte/supprimer']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\RegisterController::index' => [[], ['_controller' => 'App\\Controller\\RegisterController::index'], [], [['text', '/register']], [], [], []],
    'App\Controller\SecurityController::index' => [[], ['_controller' => 'App\\Controller\\SecurityController::index'], [], [['text', '/security']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
