<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_account' => [[], ['_controller' => 'App\\Controller\\AccountController::index'], [], [['text', '/mon-compte']], [], [], []],
    'app_account_toggle_api' => [[], ['_controller' => 'App\\Controller\\AccountController::toggleApi'], [], [['text', '/mon-compte/api/toggle']], [], [], []],
    'app_account_delete' => [[], ['_controller' => 'App\\Controller\\AccountController::deleteAccount'], [], [['text', '/mon-compte/supprimer']], [], [], []],
    'api_products' => [[], ['_controller' => 'App\\Controller\\ApiController::products'], [], [['text', '/api/products']], [], [], []],
    'app_cart' => [[], ['_controller' => 'App\\Controller\\CartController::index'], [], [['text', '/panier']], [], [], []],
    'app_cart_add' => [['id'], ['_controller' => 'App\\Controller\\CartController::add'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/panier/ajouter']], [], [], []],
    'app_cart_clear' => [[], ['_controller' => 'App\\Controller\\CartController::clear'], [], [['text', '/panier/vider']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_product_show' => [['id'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/produit']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegisterController::index'], [], [['text', '/register']], [], [], []],
    'app_security' => [[], ['_controller' => 'App\\Controller\\SecurityController::index'], [], [['text', '/security']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\AccountController::index' => [[], ['_controller' => 'App\\Controller\\AccountController::index'], [], [['text', '/mon-compte']], [], [], []],
    'App\Controller\AccountController::toggleApi' => [[], ['_controller' => 'App\\Controller\\AccountController::toggleApi'], [], [['text', '/mon-compte/api/toggle']], [], [], []],
    'App\Controller\AccountController::deleteAccount' => [[], ['_controller' => 'App\\Controller\\AccountController::deleteAccount'], [], [['text', '/mon-compte/supprimer']], [], [], []],
    'App\Controller\ApiController::products' => [[], ['_controller' => 'App\\Controller\\ApiController::products'], [], [['text', '/api/products']], [], [], []],
    'App\Controller\CartController::index' => [[], ['_controller' => 'App\\Controller\\CartController::index'], [], [['text', '/panier']], [], [], []],
    'App\Controller\CartController::add' => [['id'], ['_controller' => 'App\\Controller\\CartController::add'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/panier/ajouter']], [], [], []],
    'App\Controller\CartController::clear' => [[], ['_controller' => 'App\\Controller\\CartController::clear'], [], [['text', '/panier/vider']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\ProductController::show' => [['id'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/produit']], [], [], []],
    'App\Controller\RegisterController::index' => [[], ['_controller' => 'App\\Controller\\RegisterController::index'], [], [['text', '/register']], [], [], []],
    'App\Controller\SecurityController::index' => [[], ['_controller' => 'App\\Controller\\SecurityController::index'], [], [['text', '/security']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
